In [107]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

from sklearn.cross_validation import train_test_split
from sklearn import metrics
import statsmodels.formula.api as smf

# visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [108]:
titanic = pd.read_csv('/Users/anastasia.petrie/desktop/sfdat22/data/titanic.csv')

In [133]:
titanic.head(25)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   
20           21         0       2   
21           22         1       2   
22           23         1       3   
23           24         1       1   
24           25         0       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   
20                               Fynney, Mr. Joseph J    male  35.0      0   
21                              Beesley, Mr. Lawrence    male  34.0      0   
22                        McGowan, Miss. Anna "Annie"  female  15.0      0   
23                       Sloper, Mr. William Thompson    male  28.0      0   
24                      Palsson, Miss. Torborg Danira  female   8.0      3   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   N

In [110]:
#2. What is the null accuracy rate for predicting survival? (recall this means the probability of choosing the largest unique category, either survived or not)
titanic.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [111]:
#3. Can you think of some variables that are in the dataset that might contribute to predicting survival of the crash?
titanic.columns
#Pclass, Sex, Age, Parch, SibSp

Index([u'PassengerId', u'Survived', u'Pclass', u'Name', u'Sex', u'Age',
       u'SibSp', u'Parch', u'Ticket', u'Fare', u'Cabin', u'Embarked'],
      dtype='object')

In [112]:
#4. Define Pclass and Parch as the features, and Survived as the response.
feature_cols = ['Pclass', 'Parch']
x = titanic[feature_cols]
y = titanic['Survived']

In [113]:
linreg = LinearRegression()
linreg.fit(x, y)

print linreg.intercept_
print linreg.coef_

0.820560041245
[-0.19793906  0.05306367]


In [114]:
#5. Split the data into training and testing sets. (Hint: use the train test split modules from sklearn)
from sklearn.cross_validation import train_test_split

In [115]:
x_train, x_test, y_train, y_test \
= train_test_split(x, y)

In [116]:
#6. Fit a logistic regression model and examine the coefficients to confirm that they make intuitive sense.
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
zip(feature_cols, logreg.coef_[0])

[('Pclass', -0.8593005895351693), ('Parch', 0.22203179398098369)]

In [117]:
print logreg.predict_proba([1,4])
print logreg.predict_proba([3,0])

[[ 0.19878096  0.80121904]]
[[ 0.77079356  0.22920644]]


/Users/anastasia.petrie/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/anastasia.petrie/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [118]:
#7. Make predictions on the testing set and calculate the accuracy.
feature_cols = ['SibSp','Pclass']
a = titanic[feature_cols]
y = titanic['Survived']

In [119]:
linreg = LinearRegression()
linreg.fit(a, y)

print linreg.intercept_
print linreg.coef_

0.839494558414
[-0.00319959 -0.19664494]


In [120]:
a_train, a_test, y_train, y_test \
= train_test_split(a, y)

In [121]:
logreg = LogisticRegression()
logreg.fit(a_train, y_train)
zip(feature_cols, logreg.coef_[0])

[('SibSp', 0.0066739348081470877), ('Pclass', -0.90737287971586711)]

In [122]:
print logreg.predict_proba([1,3])
print logreg.predict_proba([3,1])

[[ 0.76857849  0.23142151]]
[[ 0.34801143  0.65198857]]


/Users/anastasia.petrie/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/anastasia.petrie/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [123]:
from sklearn import metrics
preds = logreg.predict(a)
print metrics.confusion_matrix(y, preds)

[[469  80]
 [206 136]]


In [125]:
titanic['Age'].isnull().sum()

177

In [129]:
average_age = titanic.groupby('Sex').Age.mean()
print average_age

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64


In [130]:
titanic['Age'].fillna(30)
feature_cols = ['Age','Pclass']
a = titanic[feature_cols]
y = titanic['Survived']

In [132]:
linreg = LinearRegression()
linreg.fit(a, y)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [100]:
feature_cols = ['Sex','Pclass']
x = titanic[feature_cols]
y = titanic['Survived']
linreg = LinearRegression()
linreg.fit(x, y)

print linreg.intercept_
print linreg.coef_

ValueError: could not convert string to float: male

In [ ]:
#10. Try to make up a new column (be creative!) that you think might be helpful. For example one student make a column called "is_married" which was a combination of SibSp and the name column and include this new column.
last_name = titanic['Name'].lambda x